### ISSUE TITLE
The project is using an incompatible version (AGP 8.1.0-alpha11)

### ISSUE THREAD

**Issue by juanunix** [mobiledevpro/Jetpack-Compose-ChatApp-Template#8]
The project is using an incompatible version (AGP 8.1.0-alpha11) of the Android Gradle plugin. Latest supported version is AGP 8.1.0-alpha06
See Android Studio & AGP compatibility options.

**Comment by dmitriy-chernysh** [comment]
Please use the latest canary version of Android Studio 

![image](https://user-images.githubusercontent.com/5750211/230927018-46563bcb-4692-4112-a70c-b99d5e0429d1.png)
